### ISSUE TITLE
error at Invoke-PKIAudit.ps1:333 char:5

### ISSUE THREAD

**Issue by shivarajmulimani** [GhostPack/PSPKIAudit#15]
Method invocation failed because [System.Uri] does not contain a method named 'new'.
At C:\Users\shiva\Downloads\PSPKIAudit-main\PSPKIAudit-main\Code\Invoke-PKIAudit.ps1:333 char:5
$Cache.Add([System.Uri]::new($URL), $AuthType, [System.Net.CredentialCache]: ...
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound

I'm getting above error on Windows server 2012 R2 machine

**Comment by shivarajmulimani** [comment]
I was able to fix this error, 

Here is how I debugged it,

I checked System.URI object methods in powershell, it don't had ::new() method.

The above situation is because of powershell Version 4.

Two solutions:
First one, Upgrade powershell to 5.1.
Second one, just remove ::(new) method at line 333 and just put $URL. like this - `[System.Uri]::new($URL)`

**Comment by leechristensen** [comment]
Closing due to PSPKIAudit now requiring at least Windows PowerShell 5.1 (for package management)
