### ISSUE TITLE
latest PSPKI integration test request

### ISSUE THREAD

**Issue by Crypt32** [GhostPack/PSPKIAudit#17]
I'm the author of PSPKI module which is used by PSPKIAudit. For past time I've actively worked on bug fixing in PSPKI and would like to execute integration tests with your module to ensure that the existing behavior is not broken. For example, I've fixed this issue: https://github.com/GhostPack/PSPKIAudit/issues/14 and other bugs related to certificate templates.

**Comment by leechristensen** [comment]
Thank you @Crypt32 and please excuse the delay getting this merged in.  Thanks to @PatrickOnGit work in #24, PSPKIAudit now pulls in PSPKI from the PSGallery. Thanks again for all your great work on PSPKI!

**Comment by leechristensen** [comment]
Actually, just to check @Crypt32, have these changes all been merged into the version of PSPKI on the PSGallery? I noticed that the latest version (3.7.2) was pushed in 2020

**Comment by Crypt32** [comment]
> Actually, just to check @Crypt32, have these changes all been merged into the version of PSPKI on the PSGallery? I noticed that the latest version (3.7.2) was pushed in 2020

They are merged in sources, but not yet available in PSGallery. This year, I'm planning a major upgrade of underlying PKI API library which changes type namespaces so I would test it with PSPKIAudit before and make your tool compatible with new PSPKI version.

**Comment by Crypt32** [comment]
> Initial report from my peer was they were getting a "get-certificationauthority is not recognized"

This suggests that the target machine doesn't have AD CS RSAT installed. PSPKI performs RSAT checking and if missing, dependent commands are not loaded.

**Comment by leechristensen** [comment]
There was also an issue where, if PSPKI was NOT installed, and users imported the PSPKIAudit.psm1, it would import successfully but `Get-CertificationAuthority` would fail since PSPKI was not installed. With the latest installation instructions specifying to import he PS manifest file (the psd1), this should no longer be an issue.

To your point @Crypt32, we should probably add a check for the RSAT modules to the psm1 still.

**Comment by Bildar** [comment]
Thanks. I tried the new version / instructions in a lab and a production environment. I do get PSPKI 4.0.0 now, the PSPKIAudit module installs and everything I've looked at appears to be working as expected.

**Comment by leechristensen** [comment]
Great! Thank you for confirming!
