### ISSUE TITLE
-CAName

### ISSUE THREAD

**Issue by telabmed** [GhostPack/PSPKIAudit#18]
Hi, I have an issue when i try this command 
Invoke-PKIAudit [-CAComputerName mycaserver | -CAName mylocalca

The commande -CAName is not recognized as the name of a cmdlet, functio, script file, or operable program

I also tried from the CA server same issue .

**Comment by telabmed** [comment]
Hi,
Could you  help me ?

thanks

**Comment by kaunchman** [comment]
Hi,

I also have this same issue when running Invoke-PKIAudit [-CAComputerName mycaserver | -CAName mylocalca]

The command -CAName is not recognized as the name of a cmdlet, function, script file, or operable program

Thank you.

**Comment by mojazycie** [comment]
> Hi, you have to Install power shel module pspki 

I am also running into this issue. I have imported the Powershell module and made sure that both the FQDN and CA name are correct. I have tried invoking PKIAudit without the CaName but got the following:

"The specified wildcard character pattern is not valid: [-CAComputerName . . . "

Can anyone please recommend what to do/try next?

**Comment by telabmed** [comment]
Also ad-module

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : mojazycie ***@***.***>
Envoyé : Monday, October 10, 2022 11:24:25 PM
À : GhostPack/PSPKIAudit ***@***.***>
Cc : telabmed ***@***.***>; Author ***@***.***>
Objet : Re: [GhostPack/PSPKIAudit] -CAName (Issue #18)


Hi, you have to Install power shel module pspki

I am also running into this issue. I have imported the Powershell module and made sure that both the FQDN and CA name are correct. I have tried invoking PKIAudit without the CaName but got the following:

"The specified wildcard character pattern is not valid: [-CAComputerName . . . "

Can anyone please recommend what to do/try next?

**Comment by leechristensen** [comment]
I believe you are running it incorrectly. You need to run it like this:
```
Invoke-PKIAudit -CAName TheNameOfYourCA
```
or
```
Invoke-PKIAudit -CAComputerName CA.DOMAIN.COM
```
