### ISSUE TITLE
Output objects are not correct

### ISSUE THREAD

**Issue by poortom1004** [GhostPack/PSPKIAudit#20]
Invoke-PKIAudit with Export-Csv or Out-GridView doesn't display object output correctly.
example:
Invoke-PKIAudit | Out-GridView

**Comment by leechristensen** [comment]
I cannot reproduce. Please let me know if you have steps that can reproduce it. 
<img width="764" alt="image" src="https://github.com/GhostPack/PSPKIAudit/assets/5449193/02cf8fcb-95f8-4c55-baae-be372a7f5564">
