### ISSUE TITLE
Possible to target one particular template?

### ISSUE THREAD

**Issue by twm2512** [GhostPack/PSPKIAudit#21]
When I run Invoke-PKIAudit it runs the test against the CA and all of the templates. Does anyone know if it is possible to run the test specifically against one particular template? Some of our templates have a "/" character in the name which [errors out](https://github.com/GhostPack/PSPKIAudit/issues/19) the test. Trying to run this test against one particular template that doesn't have the "/" character. Thnx

**Comment by leechristensen** [comment]
You could try removing the embedded version of PSPKI and latest version released by the author (there used to be some bugs in it bug he's made some fixes, see #17 ). We've been meaning to do this, but haven't had the cycles (PRs welcome!)

Alternative tools exist to check for privilege escalation vulns, including [Certipy](https://github.com/ly4k/Certipy) and [Certify](https://github.com/GhostPack/Certify).

**Comment by leechristensen** [comment]
I updated PSPKIAudit to use the latest version os PSPKI, but it still has issues with special characters in the name. We do not plan to support scanning an individual template, so in the mean time we'll wait for a fix from PSPKI. Other open issues are tracking this problem right now
