### ISSUE TITLE
Can this be run from Linux?

### ISSUE THREAD

**Issue by bmilliron67** [GhostPack/PSPKIAudit#25]
I have powershell for linux but can't seem to get the modules this depends on.
PS /home/kali/PSPKIAudit> Import-Module ./PSPKIAudit.psd1                                                      Import-Module: The required module 'ActiveDirectory' is not loaded. Load the module or remove the module from 'RequiredModules' in the file '/home/kali/PSPKIAudit/PSPKIAudit.psd1'.                                          
PS /home/kali/PSPKIAudit> Install-Module ActiveDirectory   
Install-Package: No match was found for the specified search criteria and module name 'ActiveDirectory'. Try Get-PSRepository                                                                                                 
to see all available registered module repositories.

**Comment by SamErde** [comment]
No, in short the Active Directory module is only supported on Windows. When used in PowerShell 7 (core) on Windows, it still relies on the WindowsCompatibility module. See https://techcommunity.microsoft.com/t5/windows-powershell/run-active-directory-commands-from-powershell-installed-on-linux/m-p/2078100 and https://learn.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps.
