### ISSUE TITLE
Invoke-PSPKIAudit not recognized

### ISSUE THREAD

**Issue by erudes1991** [GhostPack/PSPKIAudit#26]
Hello,

I have a problem and I'm pretty sure I'm doing things right.
I am trying to run this on my CA server, I have even RSAT Tools install for ADDS.
I am able to extract and install the modules but when trying to invoke I get this:

Invoke-PSPKIAudit : The term 'Invoke-PSPKIAudit' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

Not exactly sure what I'm missing, I downloaded the files, extracted them, installed the module, what am I missing?

**Comment by leechristensen** [comment]
Did you run `Import-Module .\PSPKIAudit.psm1`?

**Comment by erudes1991** [comment]
> Did you run `Import-Module .\PSPKIAudit.psm1`?

I have and I get no output, guessing that means succesful though:

<img width="309" alt="image" src="https://github.com/GhostPack/PSPKIAudit/assets/134726819/5ae130c2-1fba-48d1-ac9b-ac64763ab480">

**Comment by leechristensen** [comment]
Once it is imported, did you run `Invoke-PKIAudit`?  Alternative ways to run that cmdlet include:
```
Invoke-PKIAudit -CAComputerName CA.DOMAIN.COM
```
or
```
Invoke-PKIAudit -CAName NameOfYourCA
```

**Comment by erudes1991** [comment]
any hints? :(

**Comment by erudes1991** [comment]
I downloaded the zip, extracted it, installed the module, also AD module with RSAT, but receive that during invoking...what am I doing wrong?

**Comment by PatrickOnGit** [comment]
After downloading, did you unblock the files? Usually they are marked as 'downloaded from internet' in an additional file stream. Unfortunately the module seems to load but doesn't. After unblockin,  open a new PowerShell window as PoSh remembers that it tried but failed to load.

**Comment by SamErde** [comment]
What is your comfort level with PowerShell? Just trying to gauge how helpful to try to be here based on the above screenshot. :)

Try running just `Invoke-PKIAudit -CAComputerName VMCA1-Cont.contoso.com` **but replace "VMCA1-Cont.consoso.com** with the computer name of your own certificate authority server.

**Comment by erudes1991** [comment]
@SamErde VMCA1-Cont.contoso.com is the computer name of my CA server....

**Comment by SamErde** [comment]
So you're running this in a lab? Gotcha! Then run that command as-is: 
`Invoke-PKIAudit -CAComputerName "VMCA1-Cont.contoso.com"`

**Comment by MoppelMat** [comment]
Excuse me for chiming in, but I have the same problem.

First of all: Do I need a Server-OS to run this?
I try to make it work on my W10 Workstation, but I fail miserably.

`C:\Tools\PSPKIAudit [main ≡]> Get-WindowsCapability -Online | where Name -match "CertificateServices"


Name  : Rsat.CertificateServices.Tools~~~~0.0.1.0
State : Installed`

`C:\Tools\PSPKIAudit [main ≡]> Get-WindowsCapability -Online -Name "Rsat.*"


Name         : Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0
State        : Installed`

`C:\Tools\PSPKIAudit [main ≡]> Import-Module .\PSPKIAudit.psm1
WARNUNG: Die Namen einiger importierter Befehle auf Modul "PSPKIAudit" enthalten nicht genehmigte Verben, sodass deren Auffindbarkeit erschwert werden kann. Wenn Sie die Befehle mit nicht genehmigten
Verben finden möchten, führen Sie den Import-Module-Befehl erneut mit dem Verbose-Parameter aus. Sie können durch Eingeben von "Get-Verb" eine Liste der genehmigten Verben anzeigen.
C:\Tools\PSPKIAudit [main ≡]> Invoke-PKIAudit

  _____   _____ _____  _  _______                   _ _ _
 |  __ \ / ____|  __ \| |/ /_   _|   /\            | (_) |
 | |__) | (___ | |__) | ' /  | |    /  \  _   _  __| |_| |_
 |  ___/ \___ \|  ___/|  <   | |   / /\ \| | | |/ `  | | __|
 | |     ____) | |    | . \ _| |_ / ____ \ |_| | (_| | | |_
 |_|    |_____/|_|    |_|\_\_____/_/    \_\__,_|\__,_|_|\__|
  v0.3.6


[*] Enumerating certificate authorities with Get-AuditCertificateAuthority...

Get-CertificationAuthority : Die Benennung "Get-CertificationAuthority" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie
die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Tools\PSPKIAudit\Code\Invoke-PKIAudit.ps1:201 Zeichen:16
+         $CAs = Get-CertificationAuthority
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-CertificationAuthority:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Forry for german crap, I can translate if needed. Basically the error tells me that the command Get-CertificationAuthority was not found.

I tried with user and admin rights.

I get the same output if I include the name of my CA server, or not.

**Comment by MoppelMat** [comment]
> Just updated the readme to include instructions for install the PSPKI module and to import PSPKAudit from its manifest file (.psd1) instead of module file (.psm1). Let me know if that solves your issue @MoppelMat

that works like a charm now! thank you!
