### ISSUE TITLE
Cannot bind argument to parameter 'Username' because it is an empty string

### ISSUE THREAD

**Issue by patrick-marr-kelmar** [GhostPack/PSPKIAudit#31]
Invoke-PKIAudit  command runs, but throws this error for each CA that it discovers. 

Line |
 105 |          $CATemplates = Get-AuditCertificateTemplate @Args
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Username' because it is an empty string.

**Comment by PatrickOnGit** [comment]
Hi Patrick 

Can you please write the full command you used to call Invoke-PKIAudit?

Thank you

________________________________
Von: patrick-marr-kelmar ***@***.***>
Gesendet: Donnerstag, 5. September 2024 22:45
An: GhostPack/PSPKIAudit
Cc: Subscribed
Betreff: [GhostPack/PSPKIAudit] Cannot bind argument to parameter 'Username' because it is an empty string (Issue #31) 

Invoke-PKIAudit command runs, but throws this error for each CA that it discovers.
Line |
105 | $CATemplates = Get-AuditCertificateTemplate @Args
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot bind argument to parameter 'Username' because it is an empty string.

**Comment by SamErde** [comment]
Do you have the RSAT component for Certificate management installed along with the PSPKI module from PKI Solutions?  

Note: you must install RSAT *before* PSPKI or else PSPKI won't install the Get-CertificationAuthority function.

**Comment by patrick-marr-kelmar** [comment]
![PSPKI-Audit-2024-09-11_08-45-41](https://github.com/user-attachments/assets/61db60e5-ba71-47c4-b150-88d83b540f43)

Attached is a screenshot of the full series of commands run to Install RSAT, Install PSPKI, import PKIAudit and run Invoke-PKIAudit.

Thanks,

Pat

**Comment by SamErde** [comment]
I'm not sure what's causing that, but looked at the relevant code and noted that error occurs at this segment:

```powershell
function Test-IsCertificateAuthorityACLVulnerable {
    <#
    .SYNOPSIS
    
    Returns true if a certicate authority ACL is vulnerable.

    License: Ms-PL
    Required Dependencies: PSPKI

    .PARAMETER CAACL

    The certificate authority ACL to audit.
    #>
    [CmdletBinding()]
    Param(
        [Parameter(Position=0, Mandatory=$True)]
        [SysadminsLV.PKI.Security.AccessControl.CertSrvSecurityDescriptor]
        $CAACL
    )
    
    if( (ConvertName-ToSid $CAACL.Owner) -match $CommonLowprivPrincipals) {
        return $True
    }
# ... (partial snippet of the function)
```
...which is called from this block earlier in the script: 
```powershell
    ForEach($CA in $CAs) {
        $CAServer = $CA.ComputerName
        $CAName = $CA.Name
        Write-Verbose "[Get-AuditCertificateAuthorit] CA: '$CAServer\$CAName'"

        try {
            $CAACL = $CA | Get-CertificationAuthorityAcl
            $DACLString = (($CAACL.Access | ForEach-Object { "$($_.IdentityReference) ($($_.AccessControlType)) - $($_.Rights)"}) -join "`n")

            $EnrollmentPrincipals = ForEach($Ace in $CAACL.Access) {
                if(
                    ($Ace.AccessControlType -eq [System.Security.AccessControl.AccessControlType]::Allow) -and 
                    ($Ace.Rights.HasFlag([SysadminsLV.PKI.Security.AccessControl.CertSrvRights]::Enroll))
                ) {
                    $Ace.IdentityReference
                }
            }

            $AllowsUserSANs = Test-UserSpecifiesSAN -ComputerName $CAServer -CAName $CAName
        }
        catch {
            Write-Warning "Error enumerating ACL information for CA '$CAServer\$CAName' : $_"
        }

        $CAACLVulnerable = $False
        
        if($CAACL) {
            $CAACLVulnerable = Test-IsCertificateAuthorityACLVulnerable $CAACL
        }
```

For some reason it may be failing to convert a SID in an ACL that it found. Have you tried running with `-Verbose`?

**Comment by patrick-marr-kelmar** [comment]
Yep. That's the issue it seems. I'm seeing an error on converting a SID when I run -Verbose. 

This can be closed out. TY for helping me track down root cause!
