### ISSUE TITLE
Invoke-PKIAudit ESC8:  Protected Users group membership causes false negative

### ISSUE THREAD

**Issue by hkelley** [GhostPack/PSPKIAudit#4]
It might helpful to check for Protected Users membership in one of these functions so that you can alert the users that the NTLM relay test results will not be valid.

Get-ADCSEnrollmentEndpoint
Test-URLEndpoint

I can only generate the ESC8 finding when I run as a normal (NTLM-allowed) user ID.

**Comment by leechristensen** [comment]
Fixed with #29 thanks to @SamErde 's contribution!
