### ISSUE TITLE
Easier usage by supplying variables

### ISSUE THREAD

**Issue by Purp1eW0lf** [GhostPack/PSPKIAudit#5]
To streamline usage, I have a possible method to gather the necessary Certificate Authority and machine names, through relevant registry entries. 

A limitation however is that this is based on local machine reg values, so running on CA is required.

```powershell
#Gather variables
$CAName = (Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration").Active;
$CAHost = (Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\CertSvc\Configuration\$CAName").CAServerName;

#confirm
Write-host "$CAHost\$CAName"

#deploy with variables
Invoke-PKIAudit -CAComputerName $CAHost -CAName $CAName
```
![image](https://user-images.githubusercontent.com/44196051/123516560-9e0ba800-d694-11eb-9357-883da066ef79.png)

**Comment by leechristensen** [comment]
Thank you, but it looks like this work only when run on CA servers and we'd like to be able to run PSPKIAudit from non-CA servers as well. Thanks for the suggestion though!
