### ISSUE TITLE
"Operation is not supported on this platform." from runas /netonly

### ISSUE THREAD

**Issue by phackt** [GhostPack/PSPKIAudit#8]
Hi, did you succeed in using your module from a non joined machine (runas /netonly) ?. I'm facing this issue:

```
> Get-AuditCertificateAuthority -CAComputerName ac1.contoso.local
Exception calling "GetAdPkiContainer" with "1" argument(s): "Operation is not supported on this platform."
At C:\Users\user\Documents\tools\pentest\PSPKIAudit\PSPKI\3.7.2\Server\Get-CertificationAuthority.ps1:18 char:9
+         $DSList = [SysadminsLV.PKI.Management.ActiveDirectory.DsPkiCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PlatformNotSupportedException
```

Any call to any function of the module is propagating the same exception.
Thanks,

**Comment by braimee** [comment]
Just wanted to add a "same issue" comment.  We do our pentests from a non-domain-joined jumpbox, so having the ability to run this tool under _runas_ context would be awesome.

**Comment by Crypt32** [comment]
This is not supported. There is a little value in running PSPKIAudit module on non-domain joined machines. For example, you cannot access certificate templates from workgroups for analysis and certificate templates are big part of this module.
